experiment_name: "Test"
settings:
  top_k: 100
  variance_per_sample: 3
dataset:
  path_to_dataset: "data/dataset.csv"
  path_to_test_data: 'data/codeforces/generated_tests'
  path_to_contest_data : 'data/codeforces/data'
  cache: True

create_dataset:
  path_to_submissions: "data/submissions"
  path_to_test_data: 'data/codeforces/generated_tests'
  path_to_contest_data : 'data/codeforces/data'
  cache: True

methods:
  NaiveFixBugLLMMethod:
      vendor: 'OpenAI'
      model_name: 'gpt-5-nano'
      cache: False

  DSPyOptimizedLLMMethod:
    vendor: 'OpenAI'
    model_name: 'gpt-5-nano'
    cache: False
    model_path: 'data/models/optimized_model_gepa.json'
    
fit:
  DSPyOptimizedLLMMethod:
    vendor: 'OpenAI'
    model_name: 'gpt-5-nano'
    cache: False

output:
  path: 'data/output_small_subset_nano'