experiment_name: "Test"
settings:
  top_k: 5
  variance_per_sample: 1
dataset:
  path_to_submissions: 'data/dataset.csv'
  path_to_test_data: 'data/codeforces/generated_tests'
  path_to_contest_data : 'data/codeforces/data'
  cache: True

methods:
  NaiveFixBugLLMMethod:
      vendor: 'OpenAI'
      model_name: 'gpt-5-nano'
      
  GenerateFromScratchLLMMethod:
      vendor: 'OpenAI'
      model_name: 'gpt-5-nano'

  DSPyOptimizedLLMMethod:
    vendor: 'OpenAI'
    model_name: 'gpt-5-nano'
  
fit:
  DSPyOptimizedLLMMethod:
    vendor: 'OpenAI'
    model_name: 'gpt-5-nano'

output:
  path: 'data/output_test_val_5_fit_v2'